apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: site-app
  namespace: default
  labels:
    app: site-app
spec:
  selector:
    matchLabels:
      app: site-app
  template:
    metadata:
      labels:
        app: site-app
    spec:
      containers:
        - name: site-app
          image: 590183728861.dkr.ecr.eu-central-1.amazonaws.com/site-app:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: site-service
  namespace: default
spec:
  selector:
    app: site-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::590183728861:user/github-actions
      username: github-actions
      groups:
        - system:masters
