apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: site-app
  labels:
    app: site-app
spec:
  selector:
    matchLabels:
      app: site-app
  template:
    metadata:
      labels:
        app: site-app
    spec:
      containers:
        - name: site-app
          image: <ECR_REGISTRY>/site-app:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: site-service
spec:
  selector:
    app: site-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
