name: Build & Deploy Site to EKS (DaemonSet)

on:
  repository_dispatch:
    types: [deploy-site]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout DevOps repo
        uses: actions/checkout@v4

      - name: Checkout Site repo
        uses: actions/checkout@v4
        with:
          repository: yourusername/site-repo
          token: ${{ secrets.GH_PAT }}
          path: site

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: site-app
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./site
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Deploy as DaemonSet
        run: |
          kubectl apply -f k8s/daemonset.yaml
          kubectl rollout status daemonset/site-app
