name: Deploy to EKS

on:
  repository_dispatch:
    types: [new-image]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name dev --region ${{ secrets.AWS_REGION }}

      # Сначала применяем манифест, чтобы ресурс точно был в кластере
      - name: Apply Kubernetes manifests
        run: kubectl apply -f k8s/daemonset.yaml -n default

      # Обновляем образ контейнера
      - name: Update Docker image
        run: |
          IMAGE_TAG=${{ github.event.client_payload.image_tag }}
          kubectl set image daemonset/site-app site-app=${{ secrets.DOCKER_REGISTRY }}:$IMAGE_TAG -n default

      # Проверяем rollout
      - name: Rollout status
        run: kubectl rollout status daemonset/site-app -n default
